### ISSUE TITLE
fails on ftp, not sure if that's by design?

### ISSUE THREAD

**Issue by brumle80** [huydx/hget#11]
error message:
`unsupported protocol scheme "ftp"panic: Get ftp://ftp.eyenetworks.no/AirTies/Air%204920/Firmware/AirTies_Air4920NO-EN_FW_1.23.6.4.872.bin: unsupported protocol scheme "ftp"

goroutine 1 [running]:
panic(0x7a6ec0, 0xc82010a450)
    /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
main.FatalCheck(0x7f0c43e521b0, 0xc82010a450)
    /home/dag/go/src/github.com/huydx/hget/util.go:16 +0x106
main.NewHttpDownloader(0x7ffcb01cb1b7, 0x5d, 0x4, 0x9f7e01, 0x0)
    /home/dag/go/src/github.com/huydx/hget/http.go:58 +0x326
main.Execute(0x7ffcb01cb1b7, 0x5d, 0x0, 0x4, 0x1)
    /home/dag/go/src/github.com/huydx/hget/main.go:87 +0x4df
main.main()
    /home/dag/go/src/github.com/huydx/hget/main.go:58 +0x778
`

**Comment by huydx** [comment]
hi @brumle80 , fpt is currently not supported, i will try to support it soon.

**Comment by zQueal** [comment]
@huydx any movement on FTP support?
