### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by gonzaloserrano** [huydx/hget#3]
```
╰─○ hget http://www.grpc.io/img/grpc_inverse.svg
INFO: Resolve ip: 151.101.16.133
WARN: Target url not contain Content-Length header
INFO: Dowload size: not specified
panic: runtime error: makeslice: len out of range

goroutine 23 [running]:
panic(0x38e3c0, 0xc820136220)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
strings.Repeat(0x401108, 0x1, 0xfffffffffffffff8, 0x0, 0x0)
    /usr/local/Cellar/go/1.6.2/libexec/src/strings/strings.go:427 +0x5f
gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).write(0xc8201063c0, 0x1ce6)
    /Users/gonzalo/dev/sp/go/src/gopkg.in/cheggaaa/pb.v1/pb.go:357 +0x10e9
gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Finish.func1()
    /Users/gonzalo/dev/sp/go/src/gopkg.in/cheggaaa/pb.v1/pb.go:216 +0x5a
sync.(*Once).Do(0xc820106428, 0xc820053d38)
    /usr/local/Cellar/go/1.6.2/libexec/src/sync/once.go:44 +0xe4
gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Finish(0xc8201063c0)
    /Users/gonzalo/dev/sp/go/src/gopkg.in/cheggaaa/pb.v1/pb.go:221 +0x45
main.(*HttpDownloader).Do.func1(0xc8200ee2b0, 0xc8200fa2a0, 0xc82001a660, 0xc82005a620, 0xc82001a6c0, 0xc82001a600, 0xc8200fe0e0, 0x2, 0x7fff5fbfd005, 0x27, ...)
    /Users/gonzalo/dev/sp/go/src/github.com/huydx/hget/http.go:198 +0x9b9
created by main.(*HttpDownloader).Do
    /Users/gonzalo/dev/sp/go/src/github.com/huydx/hget/http.go:204 +0x688
```

**Comment by huydx** [comment]
@gonzaloserrano this is quite an embarrassing bug :(, i've fixed and you can pull out the newest code right now.

**Comment by gonzaloserrano** [comment]
Nah, no worries. Thanks for your time!
